/*
  *
  *  GRACENOTE, INC. PROPRIETARY INFORMATION
  *  This software is supplied under the terms of a license agreement or
  *  nondisclosure agreement with Gracenote, Inc. and may not be copied
  *  or disclosed except in accordance with the terms of that agreement.
  *  Copyright(c) 2000-2014. Gracenote, Inc. All Rights Reserved.
  *
*/

/*
* gnsdk_error_codes.h - Package code definitions and string access.
*/

/*
 * Note: all values are expressed in hexadecimal form.
 */

#ifndef	_GNSDK_ERROR_CODES_H_
#define _GNSDK_ERROR_CODES_H_

/*
* Dependencies
*/


#ifdef __cplusplus
extern "C"{
#endif


/*
* Constants
*/

/* Package/library identifiers. */
#define GNSDKERR_BASE_PKG_ID					(0x80)
#define GNSDKERR_MAX_PKG_ID						(GNSDKERR_BASE_PKG_ID+0x7D)
#define GNSDKERR_RSV_PKG_IDS					(GNSDKERR_BASE_PKG_ID+0x3f)
#define GNSDKERR_APP_PKG_IDS					(GNSDKERR_BASE_PKG_ID+0x5f)

/* Register your application package ID starting with this value */
#define GNSDKPKG_ID_APP_START					(GNSDKERR_APP_PKG_IDS+0x01)
#define GNSDKPKG_ID_APP_MAX						(GNSDKERR_MAX_PKG_ID)

/* GNSDK defined packages */
#define GNSDKPKG_SDKManager						(GNSDKERR_BASE_PKG_ID+0x00)
#define GNSDKPKG_MusicID						(GNSDKERR_BASE_PKG_ID+0x01)
#define GNSDKPKG_MusicID_File					(GNSDKERR_BASE_PKG_ID+0x02)
#define GNSDKPKG_Link							(GNSDKERR_BASE_PKG_ID+0x04)
#define GNSDKPKG_VideoID						(GNSDKERR_BASE_PKG_ID+0x05)
#define GNSDKPKG_Submit							(GNSDKERR_BASE_PKG_ID+0x06)
#define GNSDKPKG_eMMS							(GNSDKERR_BASE_PKG_ID+0x08)
#define GNSDKPKG_Playlist						(GNSDKERR_BASE_PKG_ID+0x09)
#define GNSDKPKG_Storage_SQLite					(GNSDKERR_BASE_PKG_ID+0x20)
#define GNSDKPKG_DSP							(GNSDKERR_BASE_PKG_ID+0x21)
#define GNSDKPKG_MusicID_Match					(GNSDKERR_BASE_PKG_ID+0x22)
#define GNSDKPKG_ACR							(GNSDKERR_BASE_PKG_ID+0x24)
#define GNSDKPKG_Lookup_Local					(GNSDKERR_BASE_PKG_ID+0x25)
#define GNSDKPKG_EDBInstall						(GNSDKERR_BASE_PKG_ID+0x26)
#define GNSDKPKG_EPG							(GNSDKERR_BASE_PKG_ID+0x27)
#define GNSDKPKG_MoodGrid						(GNSDKERR_BASE_PKG_ID+0x28)
#define GNSDKPKG_Storage_QNX					(GNSDKERR_BASE_PKG_ID+0x29)
#define GNSDKPKG_Lookup_FPLocal					(GNSDKERR_BASE_PKG_ID+0x30)
#define GNSDKPKG_Correlates						(GNSDKERR_BASE_PKG_ID+0x31)
#define GNSDKPKG_Taste							(GNSDKERR_BASE_PKG_ID+0x32)
#define GNSDKPKG_MusicID_Stream					(GNSDKERR_BASE_PKG_ID+0x33)
#define GNSDKPKG_Lookup_LocalStream				(GNSDKERR_BASE_PKG_ID+0x34)
#define GNSDKPKG_Rhythm							(GNSDKERR_BASE_PKG_ID+0x35)
#define GNSDKPKG_ASTREAM  						(GNSDKERR_BASE_PKG_ID+0x36)
#define GNSDKPKG_BUNDLE   						(GNSDKERR_BASE_PKG_ID+0x37)

/* GNSDK Utilities Package IDs */
#define GNSDKPKG_FP								(GNSDKERR_BASE_PKG_ID+0x40)
#define GNSDKPKG_TOC_Gen						(GNSDKERR_BASE_PKG_ID+0x41)

/* GNSKD Wrapper Package IDs */
#define GNSDKPKG_Wrapper						(GNSDKERR_BASE_PKG_ID+0x48)

/* GNSDK Reserve Package IDs */
#define GNSDKPKG_MIDFLogging					(GNSDKERR_BASE_PKG_ID+0x50)
#define GNSDKPKG_EDBIntallTextAlbums			(GNSDKERR_BASE_PKG_ID+0x51)
#define GNSDKPKG_EDBIntallTextContrib			(GNSDKERR_BASE_PKG_ID+0x52)
#define GNSDKPKG_EDBIntallTextTrack				(GNSDKERR_BASE_PKG_ID+0x53)
#define	GNSDKPKG_EDBInstallTocAlbums			(GNSDKERR_BASE_PKG_ID+0x54)
#define	GNSDKPKG_EDBInstallFPAlbums				(GNSDKERR_BASE_PKG_ID+0x55)
#define	GNSDKPKG_EDBInstallImages				(GNSDKERR_BASE_PKG_ID+0x56)
#define GNSDKPKG_TasteDebug						(GNSDKERR_BASE_PKG_ID+0x57)
#define	GNSDKPKG_EDBInstallErrors				(GNSDKERR_BASE_PKG_ID+0x58)

/* Error Codes */
#define GNSDKERR_BASE_CODE						(0x0)

/* General Errors */
#define GNSDKERR_NoError						(GNSDKERR_BASE_CODE)
#define GNSDKERR_InvalidArg						(GNSDKERR_BASE_CODE+0x0001)
#define GNSDKERR_NoMemory						(GNSDKERR_BASE_CODE+0x0002)
#define GNSDKERR_NotFound						(GNSDKERR_BASE_CODE+0x0003)
#define GNSDKERR_IOError						(GNSDKERR_BASE_CODE+0x0004)
#define GNSDKERR_ReadOnly						(GNSDKERR_BASE_CODE+0x0005)
#define GNSDKERR_Busy							(GNSDKERR_BASE_CODE+0x0006)
#define GNSDKERR_NotInited						(GNSDKERR_BASE_CODE+0x0007)
#define GNSDKERR_BufferTooSmall					(GNSDKERR_BASE_CODE+0x0008)
#define GNSDKERR_InvalidFormat					(GNSDKERR_BASE_CODE+0x0009)
#define GNSDKERR_InitFailed						(GNSDKERR_BASE_CODE+0x000A)
#define GNSDKERR_Unsupported					(GNSDKERR_BASE_CODE+0x000B)
#define GNSDKERR_InvalidData					(GNSDKERR_BASE_CODE+0x000C)
#define GNSDKERR_InvalidCall					(GNSDKERR_BASE_CODE+0x000D)
#define GNSDKERR_HashingError					(GNSDKERR_BASE_CODE+0x000E)
#define GNSDKERR_NotApplicable					(GNSDKERR_BASE_CODE+0x000F)
#define GNSDKERR_Deregistered					(GNSDKERR_BASE_CODE+0x003B)
#define GNSDKERR_Unexpected						(GNSDKERR_BASE_CODE+0x003C)
#define GNSDKERR_IckyError						(GNSDKERR_BASE_CODE+0x003D)
#define GNSDKERR_Unknown						(GNSDKERR_BASE_CODE+0x003E)
#define GNSDKERR_LibraryNotLoaded				(GNSDKERR_BASE_CODE+0x003F)

/* File System Subsystem */
#define GNSDKERR_FileInvalidAccess				(GNSDKERR_BASE_CODE+0x0040)
#define GNSDKERR_FileNotFound					(GNSDKERR_BASE_CODE+0x0041)
#define GNSDKERR_FileExists						(GNSDKERR_BASE_CODE+0x0042)
#define GNSDKERR_FileNoSpace					(GNSDKERR_BASE_CODE+0x0043)
#define GNSDKERR_FileTooManyOpen				(GNSDKERR_BASE_CODE+0x0044)
#define GNSDKERR_FileInvalidHandle				(GNSDKERR_BASE_CODE+0x0045)
#define GNSDKERR_FileInvalidName				(GNSDKERR_BASE_CODE+0x0046)
#define GNSDKERR_FileInvalidFolder				(GNSDKERR_BASE_CODE+0x0047)
#define GNSDKERR_FileTooLarge					(GNSDKERR_BASE_CODE+0x0048)
#define GNSDKERR_EndOfFile						(GNSDKERR_BASE_CODE+0x0049)
#define GNSDKERR_DirNotEmpty					(GNSDKERR_BASE_CODE+0x0050)
#define GNSDKERR_FileInvalidOffset				(GNSDKERR_BASE_CODE+0x0051)
#define GNSDKERR_WriteOnly						(GNSDKERR_BASE_CODE+0x0052)
#define GNSDKERR_AppendOnly						(GNSDKERR_BASE_CODE+0x0053)

/* Remote Communications Management */
#define GNSDKERR_NoMoreConnections				(GNSDKERR_BASE_CODE+0x0080)
#define GNSDKERR_CommInvalidAddress				(GNSDKERR_BASE_CODE+0x0081)
#define GNSDKERR_CommInvalidHandle				(GNSDKERR_BASE_CODE+0x0082)
#define GNSDKERR_CommHostDown					(GNSDKERR_BASE_CODE+0x0083)
#define GNSDKERR_Timeout						(GNSDKERR_BASE_CODE+0x0084)
#define GNSDKERR_HTTPClientError				(GNSDKERR_BASE_CODE+0x0085)
#define GNSDKERR_HTTPServerError				(GNSDKERR_BASE_CODE+0x0086)
#define GNSDKERR_HTTPInvalidURL					(GNSDKERR_BASE_CODE+0x0087)
#define GNSDKERR_ConnectionRefused				(GNSDKERR_BASE_CODE+0x0088)
#define GNSDKERR_HTTPInvalidHeaderFormat		(GNSDKERR_BASE_CODE+0x0089)
#define GNSDKERR_HTTPMovedError					(GNSDKERR_BASE_CODE+0x008A)
#define GNSDKERR_Disconnected					(GNSDKERR_BASE_CODE+0x008B)
#define GNSDKERR_HTTPCancelled					(GNSDKERR_BASE_CODE+0x008C)
#define GNSDKERR_ConnectionReset				(GNSDKERR_BASE_CODE+0x008D)
#define GNSDKERR_CommNotAvailable 				(GNSDKERR_BASE_CODE+0x008E)

/* Crytographic Subsystem */
#define GNSDKERR_UnsupportedAlg					(GNSDKERR_BASE_CODE+0x00C0)

#define GNSDKERR_BadXMLFormat					(GNSDKERR_BASE_CODE+0x00C1)
#define GNSDKERR_UnknownVersion					(GNSDKERR_BASE_CODE+0x00C2)
#define GNSDKERR_DataError						(GNSDKERR_BASE_CODE+0x00C3)
#define	GNSDKERR_InvalidTOC						(GNSDKERR_BASE_CODE+0x00C4)

/* Micro XML Package */
#define GNSDKERR_SyntaxError					(GNSDKERR_BASE_CODE+0x0120)
#define GNSDKERR_IllegalCharacter				(GNSDKERR_BASE_CODE+0x0121)
#define GNSDKERR_UnexpectedEndOfInput			(GNSDKERR_BASE_CODE+0x0122)
#define GNSDKERR_NothingAtPath					(GNSDKERR_BASE_CODE+0x0123)
#define GNSDKERR_DisallowedStructure			(GNSDKERR_BASE_CODE+0x0124)

/* Online Protocol */
#define GNSDKERR_WrongServerPublicKey			(GNSDKERR_BASE_CODE+0x0160)
#define GNSDKERR_WrongClientPublicKey			(GNSDKERR_BASE_CODE+0x0161)
#define GNSDKERR_ServerError					(GNSDKERR_BASE_CODE+0x0162)
#define GNSDKERR_ServerEncryptionError			(GNSDKERR_BASE_CODE+0x0163)
#define GNSDKERR_MaxRedirects					(GNSDKERR_BASE_CODE+0x0164)
#define GNSDKERR_InvalidClientID				(GNSDKERR_BASE_CODE+0x0165)
#define GNSDKERR_InvalidUserID					(GNSDKERR_BASE_CODE+0x0166)
#define GNSDKERR_QuotaExceeded					(GNSDKERR_BASE_CODE+0x0167)
#define GNSDKERR_UserNotRegistered				(GNSDKERR_BASE_CODE+0x0168)
#define GNSDKERR_ClientUserMismatch				(GNSDKERR_BASE_CODE+0x0169)

#define GNSDKERR_Aborted						(GNSDKERR_BASE_CODE+0x01A0)
#define GNSDKERR_NotReady						(GNSDKERR_BASE_CODE+0x01A1)
#define GNSDKERR_NothingToDo					(GNSDKERR_BASE_CODE+0x01A2)
#define GNSDKERR_InvalidInputObject				(GNSDKERR_BASE_CODE+0x01A3)
#define GNSDKERR_InsufficientInputData			(GNSDKERR_BASE_CODE+0x01A4)

/* GCSP Transport */
#define GNSDKERR_CorruptEncryptData				(GNSDKERR_BASE_CODE+0x0200)
#define GNSDKERR_CorruptCompressData			(GNSDKERR_BASE_CODE+0x0201)
#define GNSDKERR_CommandError					(GNSDKERR_BASE_CODE+0x0202)
#define GNSDKERR_ClientCompression				(GNSDKERR_BASE_CODE+0x0203)
#define GNSDKERR_ClientEncryption				(GNSDKERR_BASE_CODE+0x0204)
#define GNSDKERR_GEMPError						(GNSDKERR_BASE_CODE+0x0205)

#define GNSDKERR_UnknownResponseCode			(GNSDKERR_BASE_CODE+0x0206)
#define GNSDKERR_ClientError					(GNSDKERR_BASE_CODE+0x0207)
#define GNSDKERR_GeneralError					(GNSDKERR_BASE_CODE+0x0208)
#define GNSDKERR_IncorrectUsage					(GNSDKERR_BASE_CODE+0x0209)

/* Compression */
#define GNSDKERR_UnknownCompressionType			(GNSDKERR_BASE_CODE+0x0240)

/* Thread */
#define GNSDKERR_TooMany						(GNSDKERR_BASE_CODE+0x0280)
#define GNSDKERR_Deadlock						(GNSDKERR_BASE_CODE+0x0281)
#define GNSDKERR_NoResources					(GNSDKERR_BASE_CODE+0x0282)
#define GNSDKERR_Interrupted					(GNSDKERR_BASE_CODE+0x0283)
#define GNSDKERR_PermissionError				(GNSDKERR_BASE_CODE+0x0284)
#define GNSDKERR_ThreadTerminated				(GNSDKERR_BASE_CODE+0x0285)

/* Lists */
#define GNSDKERR_ListInvalidFile				(GNSDKERR_BASE_CODE+0x02D0)
#define GNSDKERR_ListUnavailable				(GNSDKERR_BASE_CODE+0x02D1)
#define GNSDKERR_ListInvalidLevel				(GNSDKERR_BASE_CODE+0x02D2)
#define GNSDKERR_LocaleNotSet					(GNSDKERR_BASE_CODE+0x02D3)
#define GNSDKERR_ListUpdateNeeded				(GNSDKERR_BASE_CODE+0x02D4)
#define GNSDKERR_ListStoreUnavailable			(GNSDKERR_BASE_CODE+0x02D5)

/* GDO Errors */
#define GNSDKERR_TypeMismatch					(GNSDKERR_BASE_CODE+0x0300)

/* Handle Errors */
#define GNSDKERR_HandleObjectInvalid			(GNSDKERR_BASE_CODE+0x0320)	/* handle reference invalid */
#define GNSDKERR_HandleObjectWrongType			(GNSDKERR_BASE_CODE+0x0321)	/* handle passed to incorrect API for object */
#define GNSDKERR_HandleObjectMismatch			(GNSDKERR_BASE_CODE+0x0322)	/* handle can't perform operation with parameter */

/* Submit Errors */
#define GNSDKERR_MissingField					(GNSDKERR_BASE_CODE+0x0340)
#define GNSDKERR_InvalidContents				(GNSDKERR_BASE_CODE+0x0341)
#define GNSDKERR_NotEditable					(GNSDKERR_BASE_CODE+0x0342)

/* DataType Errors */
#define GNSDKERR_DataCorruption					(GNSDKERR_BASE_CODE+0x0360)
#define GNSDKERR_IndexOutOfRange				(GNSDKERR_BASE_CODE+0x0361)
#define GNSDKERR_WrongValueType					(GNSDKERR_BASE_CODE+0x0362)
#define GNSDKERR_BadKeyValue					(GNSDKERR_BASE_CODE+0x0363)
#define GNSDKERR_LateDataUpdate					(GNSDKERR_BASE_CODE+0x0364)
#define GNSDKERR_DoDefaultProcessing			(GNSDKERR_BASE_CODE+0x0365)
#define GNSDKERR_InvalidPath					(GNSDKERR_BASE_CODE+0x0366)
#define GNSDKERR_SetsIncompatible				(GNSDKERR_BASE_CODE+0x0367)
#define GNSDKERR_DuplicateValue					(GNSDKERR_BASE_CODE+0x0368)

/* String Errors */
#define GNSDKERR_InvalidUTF8					(GNSDKERR_BASE_CODE+0x03A0)
#define GNSDKERR_InvalidUCS2					(GNSDKERR_BASE_CODE+0x03A1)

/* General low level subsystem errors */
#define GNSDKERR_CommunicationsError			(GNSDKERR_BASE_CODE+0x0400)
#define GNSDKERR_QueryError						(GNSDKERR_BASE_CODE+0x0401)
#define GNSDKERR_CDSError						(GNSDKERR_BASE_CODE+0x0402)
#define GNSDKERR_DataEncodeError				(GNSDKERR_BASE_CODE+0x0403)
#define GNSDKERR_CompressionError				(GNSDKERR_BASE_CODE+0x0404)
#define GNSDKERR_EncryptionError				(GNSDKERR_BASE_CODE+0x0405)

/* Crypto errors */
#define GNSDKERR_InvalidKey						(GNSDKERR_BASE_CODE+0x0410)
#define GNSDKERR_InvalidSignature				(GNSDKERR_BASE_CODE+0x0411)

/* License Errors */
#define GNSDKERR_LicenseInvalid					(GNSDKERR_BASE_CODE+0x0420)
#define GNSDKERR_LicenseDisallowed				(GNSDKERR_BASE_CODE+0x0421)
#define GNSDKERR_LicenseExpired					(GNSDKERR_BASE_CODE+0x0422)
#define GNSDKERR_LicenseTrialExpired			(GNSDKERR_BASE_CODE+0x0423)

/* Fingerprint Errors */
#define GNSDKERR_TemporalDiscontinuity			(GNSDKERR_BASE_CODE+0x0440)
#define GNSDKERR_SilentAudio					(GNSDKERR_BASE_CODE+0x0441)

/* Local Storage Errors */
#define GNSDKERR_LocalDatabaseNotFound			(GNSDKERR_BASE_CODE+0x0500)
#define GNSDKERR_InvalidSchema					(GNSDKERR_BASE_CODE+0x0501)
#define GNSDKERR_SchemaMismatch					(GNSDKERR_BASE_CODE+0x0502)
#define GNSDKERR_EndOfRecords					(GNSDKERR_BASE_CODE+0x0503)
#define GNSDKERR_InvalidRecord					(GNSDKERR_BASE_CODE+0x0504)
#define GNSDKERR_InvalidStorage					(GNSDKERR_BASE_CODE+0x0505)
#define GNSDKERR_InvalidIterator				(GNSDKERR_BASE_CODE+0x0506)
#define GNSDKERR_DuplicateRecord				(GNSDKERR_BASE_CODE+0x0507)
#define GNSDKERR_LocalDatabaseNotEnabled		(GNSDKERR_BASE_CODE+0x0508)
#define GNSDKERR_LocalDatabaseLocationNotSet	(GNSDKERR_BASE_CODE+0x0509)

/* DB errors */
#define GNSDKERR_NestedCall						(GNSDKERR_BASE_CODE+0x0521)
/*#define	GNSDKSERR_PermissionError			(GNSDKERR_BASE_CODE+0x0522)*/
#define GNSDKERR_ReadErr						(GNSDKERR_BASE_CODE+0x0523)
#define GNSDKERR_WriteErr						(GNSDKERR_BASE_CODE+0x0524)
/*#define	GNSDKERR_UnknownVersion				(GNSDKERR_BASE_CODE+0x0525)*/
#define GNSDKERR_InvalidFile					(GNSDKERR_BASE_CODE+0x0526)
#define GNSDKERR_AlreadyAdded					(GNSDKERR_BASE_CODE+0x0527)
#define GNSDKERR_InvalidBlock					(GNSDKERR_BASE_CODE+0x0528)
/*#define	GNSDKERR_Aborted					(GNSDKERR_BASE_CODE+0x0529)*/
#define GNSDKERR_NoSpace						(GNSDKERR_BASE_CODE+0x052A)
#define	GNSDKERR_BadIndex						(GNSDKERR_BASE_CODE+0x052B)
#define GNSDKERR_BadFreeList					(GNSDKERR_BASE_CODE+0x052C)
#define	GNSDKERR_BadRecord						(GNSDKERR_BASE_CODE+0x052D)
/*#define	GNSDKERR_BadBlock					(GNSDKERR_BASE_CODE+0x052E)*/
#define	GNSDKERR_IndexPastEOF					(GNSDKERR_BASE_CODE+0x052F)
#define	GNSDKERR_RecordPastEOF					(GNSDKERR_BASE_CODE+0x0530)
#define	GNSDKERR_IndexInFreeList				(GNSDKERR_BASE_CODE+0x0531)
#define	GNSDKERR_RecordInFreeList				(GNSDKERR_BASE_CODE+0x0532)
#define	GNSDKERR_BlockInFreeList				(GNSDKERR_BASE_CODE+0x0533)
#define GNSDKERR_IncompatibleDBs				(GNSDKERR_BASE_CODE+0x0534)
#define GNSDKERR_KeyNotRead						(GNSDKERR_BASE_CODE+0x0535)
#define GNSDKERR_InvalidByteOrder				(GNSDKERR_BASE_CODE+0x0536)
/*#define GNSDKERR_UnknownFSError				(GNSDKERR_BASE_CODE+0x0537)*/
#define GNSDKERR_BadHeader						(GNSDKERR_BASE_CODE+0x0539)
/*#define	GNSDKERR_CriticalSection			(GNSDKERR_BASE_CODE+0x053A)*/
#define	GNSDKERR_ThreadError					(GNSDKERR_BASE_CODE+0x053B)
#define	GNSDKERR_ReadLocked						(GNSDKERR_BASE_CODE+0x053C)
#define	GNSDKERR_WriteLocked					(GNSDKERR_BASE_CODE+0x053D)
#define	GNSDKERR_CorruptDB						(GNSDKERR_BASE_CODE+0x053F)

/* Protocol Buffers */
#define	GNSDKERR_DataTooShort					(GNSDKERR_BASE_CODE+0x0580)
#define	GNSDKERR_InvalidWireType				(GNSDKERR_BASE_CODE+0x0581)
#define	GNSDKERR_ParsingError					(GNSDKERR_BASE_CODE+0x0582)
#define	GNSDKERR_UnterminatedVarInt				(GNSDKERR_BASE_CODE+0x0583)

/* Playlist Errors */
#define GNSDKERR_SeedRequired					(GNSDKERR_BASE_CODE+0x0600)
#define GNSDKERR_StatementError					(GNSDKERR_BASE_CODE+0x0601)

/* GNServer errors - these may not exist in any SDKs but they are used in the JNIs */
#define GNSDKERR_Ambiguous						(GNSDKERR_BASE_CODE+0x0650)

/* ACR errors */
#define GNSDKERR_MissingListingData				(GNSDKERR_BASE_CODE+0x0700)

/* FP Local errors */
#define GNSDKERR_InvalidDate					(GNSDKERR_BASE_CODE+0x0740)
#define GNSDKERR_InvalidChecksum				(GNSDKERR_BASE_CODE+0x0741)

/* Taste Profile */
#define GNSDKERR_CorrelateSet					(GNSDKERR_BASE_CODE+0x0780)
#define GNSDKERR_ParamSet						(GNSDKERR_BASE_CODE+0x0781)

/* Rhythm Radio */
#define GNSDKERR_SeedInvalid					(GNSDKERR_BASE_CODE+0x0790)
#define GNSDKERR_SeedLimitReached				(GNSDKERR_BASE_CODE+0x0791)
#define GNSDKERR_SeedsLocked					(GNSDKERR_BASE_CODE+0x0792)

/***************/
/* ERROR VALUES*/
/***************/

/* Errors returned from the SDK Manager */
#define SDKMGRERR_NoError					GNSDKERR_NoError
#define SDKMGRERR_InvalidArg				GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_InvalidArg)
#define SDKMGRERR_InvalidCall				GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_InvalidCall)
#define SDKMGRERR_InitFailed				GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_InitFailed)
#define SDKMGRERR_LicenseInvalid			GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_LicenseInvalid)
#define SDKMGRERR_LicenseDisallowed			GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_LicenseDisallowed)
#define SDKMGRERR_LicenseExpired			GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_LicenseExpired)
#define SDKMGRERR_LicenseTrialExpired		GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_LicenseTrialExpired)
#define SDKMGRERR_NotInited					GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_NotInited)
#define SDKMGRERR_NotFound					GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_NotFound)
#define SDKMGRWARN_NotFound					GNSDKERR_MAKE_WARNING(GNSDKPKG_SDKManager, GNSDKERR_NotFound)
#define SDKMGRERR_NoMemory					GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_NoMemory)
#define SDKMGRERR_Unsupported				GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_Unsupported)
#define SDKMGRWARN_Unsupported				GNSDKERR_MAKE_WARNING(GNSDKPKG_SDKManager, GNSDKERR_Unsupported)
#define SDKMGRERR_Busy						GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_Busy)
#define SDKMGRERR_Deregistered				GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_Deregistered)
#define SDKMGRERR_InvalidFormat				GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_InvalidFormat)
#define SDKMGRERR_HandleObjectInvalid		GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_HandleObjectInvalid)
#define SDKMGRERR_HandleObjectWrongType		GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_HandleObjectWrongType)
#define SDKMGRERR_HandleObjectMismatch		GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_HandleObjectMismatch)
#define SDKMGRERR_QueryError				GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_QueryError)
#define SDKMGRERR_Timeout					GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_Timeout)
#define SDKMGRERR_CommunicationsError		GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_CommunicationsError)
#define SDKMGRERR_CDSError					GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_CDSError)
#define SDKMGRERR_DataEncodeError			GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_DataEncodeError)
#define SDKMGRERR_CompressionError			GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_CompressionError)
#define SDKMGRERR_EncryptionError			GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_EncryptionError)
#define SDKMGRERR_IncorrectUsage			GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_IncorrectUsage)
#define SDKMGRERR_IckyError					GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_IckyError)
#define SDKMGRERR_InvalidClientID			GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_InvalidClientID)
#define SDKMGRERR_InvalidUserID				GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_InvalidUserID)
#define SDKMGRERR_QuotaExceeded				GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_QuotaExceeded)
#define SDKMGRERR_InvalidSchema				GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_InvalidSchema)
#define SDKMGRERR_SchemaMismatch			GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_SchemaMismatch)
#define SDKMGRERR_LocalDBSchemaMismatch		GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_SchemaMismatch)
#define SDKMGRWARN_ListUnavailable			GNSDKERR_MAKE_WARNING(GNSDKPKG_SDKManager, GNSDKERR_ListUnavailable)
#define SDKMGRERR_ListUnavailable			GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_ListUnavailable)
#define SDKMGRERR_ServerError				GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_ServerError)
#define SDKMGRWARN_LocaleNotSet				GNSDKERR_MAKE_WARNING(GNSDKPKG_SDKManager, GNSDKERR_LocaleNotSet)
#define SDKMGRERR_LocaleNotSet				GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_LocaleNotSet)
#define SDKMGRERR_DuplicateValue			GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_DuplicateValue)
#define SDKMGRERR_Aborted					GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_Aborted)
#define SDKMGRWARN_Aborted					GNSDKERR_MAKE_WARNING(GNSDKPKG_SDKManager, GNSDKERR_Aborted)
#define SDKMGRERR_ListUpdateNeeded			GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_ListUpdateNeeded)
#define SDKMGRERR_OutOfRange				GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_IndexOutOfRange)
#define SDKMGRWARN_ListStoreUnavailable		GNSDKERR_MAKE_WARNING(GNSDKPKG_SDKManager, GNSDKERR_ListStoreUnavailable)
#define SDKMGRERR_UserNotRegistered			GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_UserNotRegistered)
#define SDKMGRERR_ClientUserMismatch		GNSDKERR_MAKE_ERROR(GNSDKPKG_SDKManager, GNSDKERR_ClientUserMismatch)
#define SDKMGRWARN_TypeMismatch				GNSDKERR_MAKE_WARNING(GNSDKPKG_SDKManager, GNSDKERR_TypeMismatch)

/* Errors returned from the MusicID-File SDK */
#define MIDFERR_NoError						GNSDKERR_NoError
#define MIDFERR_InvalidArg					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_InvalidArg)
#define MIDFERR_InitFailed					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_InitFailed)
#define MIDFERR_Unsupported					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_Unsupported)
#define MIDFWARN_Unsupported				GNSDKERR_MAKE_WARNING(GNSDKPKG_MusicID_File, GNSDKERR_Unsupported)
#define MIDFERR_NoMemory					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_NoMemory)
#define MIDFERR_NotReady					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_NotReady)
#define MIDFERR_NotInited					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_NotInited)
#define MIDFERR_NotFound					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_NotFound)
#define MIDFWARN_NotFound					GNSDKERR_MAKE_WARNING(GNSDKPKG_MusicID_File, GNSDKERR_NotFound)
#define MIDFERR_HandleObjectInvalid			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_HandleObjectInvalid)
#define MIDFERR_HandleObjectWrongType		GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_HandleObjectWrongType)
#define MIDFERR_UnsupportedAlg				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_UnsupportedAlg)
#define MIDFERR_StillProcessing				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_Busy)
#define MIDFERR_NotProcessing				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_Unexpected)
#define MIDFWARN_NotProcessing				GNSDKERR_MAKE_WARNING(GNSDKPKG_MusicID_File, GNSDKERR_Unexpected)
#define MIDFERR_InvalidCall					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_InvalidCall)
#define MIDFERR_Aborted						GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_Aborted)
#define MIDFWARN_Aborted					GNSDKERR_MAKE_WARNING(GNSDKPKG_MusicID_File, GNSDKERR_Aborted)
#define MIDFERR_Timeout						GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_Timeout)
#define MIDFWARN_Timeout					GNSDKERR_MAKE_WARNING(GNSDKPKG_MusicID_File, GNSDKERR_Timeout)
#define MIDFERR_IdentExists					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_FileExists)
#define MIDFERR_InvalidFormat				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_InvalidFormat)
#define MIDFERR_IncompatibleDBs				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_IncompatibleDBs)
#define MIDFERR_FileNotFound   				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_FileNotFound)
#define MIDFERR_NothingToDo					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_NothingToDo)
#define MIDFWARN_NothingToDo				GNSDKERR_MAKE_WARNING(GNSDKPKG_MusicID_File, GNSDKERR_NothingToDo)
#define MIDFERR_LicenseDisallowed			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_LicenseDisallowed)
#define MIDFERR_LicenseExpired				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_LicenseExpired)
#define MIDFERR_LicenseTrialExpired			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_LicenseTrialExpired)
#define MIDFERR_InvalidClientID				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_InvalidClientID)
#define MIDFERR_InvalidUserID				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_InvalidUserID)
#define MIDFERR_QuotaExceeded				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_QuotaExceeded)
#define MIDFERR_QueryError					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_QueryError)
#define MIDFERR_CDSError					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_CDSError)
#define MIDFERR_CommunicationsError			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_CommunicationsError)
#define MIDFERR_DataEncodeError				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_DataEncodeError)
#define MIDFERR_CompressionError			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_CompressionError)
#define MIDFERR_EncryptionError				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_EncryptionError)
#define MIDFERR_ThreadTerminated			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_ThreadTerminated)
#define MIDFWARN_ThreadTerminated			GNSDKERR_MAKE_WARNING(GNSDKPKG_MusicID_File, GNSDKERR_ThreadTerminated)
#define MIDFERR_LibraryNotLoaded			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_LibraryNotLoaded)
#define MIDFERR_LocaleNotSet				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_LocaleNotSet)
#define MIDFERR_InvalidUTF8					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_File, GNSDKERR_InvalidUTF8)

/* Errors returned from the MusicID-Stream SDK */
#define MIDSERR_NoError						GNSDKERR_NoError
#define MIDSERR_InvalidArg					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_InvalidArg)
#define MIDSERR_InitFailed					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_InitFailed)
#define MIDSERR_Unsupported					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_Unsupported)
#define MIDSWARN_Unsupported				GNSDKERR_MAKE_WARNING(GNSDKPKG_MusicID_Stream, GNSDKERR_Unsupported)
#define MIDSERR_NoMemory					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_NoMemory)
#define MIDSERR_NotReady					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_NotReady)
#define MIDSWARN_NotReady					GNSDKERR_MAKE_WARNING(GNSDKPKG_MusicID_Stream, GNSDKERR_NotReady)
#define MIDSERR_NotInited					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_NotInited)
#define MIDSERR_NotFound					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_NotFound)
#define MIDSWARN_NotFound					GNSDKERR_MAKE_WARNING(GNSDKPKG_MusicID_Stream, GNSDKERR_NotFound)
#define MIDSERR_HandleObjectInvalid			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_HandleObjectInvalid)
#define MIDSERR_HandleObjectWrongType		GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_HandleObjectWrongType)
#define MIDSERR_UnsupportedAlg				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_UnsupportedAlg)
#define MIDSERR_StillProcessing				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_Busy)
#define MIDSERR_NotProcessing				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_Unexpected)
#define MIDSWARN_NotProcessing				GNSDKERR_MAKE_WARNING(GNSDKPKG_MusicID_Stream, GNSDKERR_Unexpected)
#define MIDSERR_InvalidCall					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_InvalidCall)
#define MIDSERR_Aborted						GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_Aborted)
#define MIDSWARN_Aborted					GNSDKERR_MAKE_WARNING(GNSDKPKG_MusicID_Stream, GNSDKERR_Aborted)
#define MIDSERR_Timeout						GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_Timeout)
#define MIDSWARN_Timeout					GNSDKERR_MAKE_WARNING(GNSDKPKG_MusicID_Stream, GNSDKERR_Timeout)
#define MIDSERR_IdentExists					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_FileExists)
#define MIDSERR_InvalidFormat				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_InvalidFormat)
#define MIDSERR_IncompatibleDBs				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_IncompatibleDBs)
#define MIDSERR_FileNotFound   				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_FileNotFound)
#define MIDSERR_NothingToDo					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_NothingToDo)
#define MIDSERR_LicenseDisallowed			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_LicenseDisallowed)
#define MIDSERR_LicenseExpired				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_LicenseExpired)
#define MIDSERR_LicenseTrialExpired			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_LicenseTrialExpired)
#define MIDSERR_InvalidClientID				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_InvalidClientID)
#define MIDSERR_InvalidUserID				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_InvalidUserID)
#define MIDSERR_QuotaExceeded				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_QuotaExceeded)
#define MIDSERR_QueryError					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_QueryError)
#define MIDSERR_CDSError					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_CDSError)
#define MIDSERR_CommunicationsError			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_CommunicationsError)
#define MIDSERR_DataEncodeError				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_DataEncodeError)
#define MIDSERR_CompressionError			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_CompressionError)
#define MIDSERR_EncryptionError				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_EncryptionError)
#define MIDSERR_ThreadTerminated			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_ThreadTerminated)
#define MIDSWARN_ThreadTerminated			GNSDKERR_MAKE_WARNING(GNSDKPKG_MusicID_Stream, GNSDKERR_ThreadTerminated)
#define MIDSERR_LibraryNotLoaded			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_LibraryNotLoaded)
#define MIDSERR_LocaleNotSet				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_LocaleNotSet)
#define MIDSERR_InvalidUTF8					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_InvalidUTF8)
#define MIDSERR_OutOfRange					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_IndexOutOfRange)
#define MIDSERR_InvalidData					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_InvalidData)
#define MIDSERR_Busy						GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_Busy)
#define MIDSERR_InsufficientInputData		GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_InsufficientInputData)
#define MIDSWARN_InsufficientInputData		GNSDKERR_MAKE_WARNING(GNSDKPKG_MusicID_Stream, GNSDKERR_InsufficientInputData)
#define MIDSERR_IncorrectUsage				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Stream, GNSDKERR_IncorrectUsage)
#define MIDSWARN_SilentAudio				GNSDKERR_MAKE_WARNING(GNSDKPKG_MusicID_Stream, GNSDKERR_SilentAudio)

/* Errors returned from the MusicID SDK */
#define MIDERR_NoError						GNSDKERR_NoError
#define MIDERR_NotInited					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_NotInited)
#define MIDERR_InvalidArg					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_InvalidArg)
#define MIDERR_InitFailed					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_InitFailed)
#define MIDERR_NoMemory						GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_NoMemory)
#define MIDERR_Unsupported					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_Unsupported)
#define MIDERR_HandleObjectInvalid			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_HandleObjectInvalid)
#define MIDERR_HandleObjectWrongType		GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_HandleObjectWrongType)
#define MIDERR_QueryError					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_QueryError)
#define MIDERR_CDSError						GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_CDSError)
#define MIDERR_Timeout						GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_Timeout)
#define MIDERR_CommunicationsError			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_CommunicationsError)
#define MIDERR_NotFound						GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_NotFound)
#define MIDWARN_NotFound					GNSDKERR_MAKE_WARNING(GNSDKPKG_MusicID, GNSDKERR_NotFound)
#define MIDERR_OutOfRange					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_IndexOutOfRange)
#define MIDERR_InvalidInputObject			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_InvalidInputObject)
#define MIDERR_BadXMLFormat					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_BadXMLFormat)
#define MIDERR_UnknownResponseCode			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_UnknownResponseCode)
#define MIDERR_InvalidTOC					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_InvalidTOC)
#define MIDERR_DataEncodeError				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_DataEncodeError)
#define MIDERR_CompressionError				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_CompressionError)
#define MIDERR_EncryptionError				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_EncryptionError)
#define MIDERR_InsufficientInputData		GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_InsufficientInputData)
#define MIDERR_LicenseDisallowed			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_LicenseDisallowed)
#define MIDERR_LicenseExpired				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_LicenseExpired)
#define MIDERR_LicenseTrialExpired			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_LicenseTrialExpired)
#define MIDERR_Busy							GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_Busy)
#define MIDERR_InvalidClientID				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_InvalidClientID)
#define MIDERR_InvalidUserID				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_InvalidUserID)
#define MIDERR_QuotaExceeded				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_QuotaExceeded)
#define MIDERR_LibraryNotLoaded				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_LibraryNotLoaded)
#define MIDERR_LocaleNotSet					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_LocaleNotSet)
#define MIDERR_InvalidUTF8					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_InvalidUTF8)
#define MIDERR_InvalidData					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_InvalidData)
#define MIDERR_Aborted						GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_Aborted)
#define MIDWARN_Aborted						GNSDKERR_MAKE_WARNING(GNSDKPKG_MusicID, GNSDKERR_Aborted)
#define MIDERR_IncorrectUsage				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_IncorrectUsage)
#define MIDERR_NothingToDo					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID, GNSDKERR_NothingToDo)
#define MIDWARN_SilentAudio					GNSDKERR_MAKE_WARNING(GNSDKPKG_MusicID, GNSDKERR_SilentAudio)

/* Errors returned from the Link SDK */
#define LINKERR_NoError						GNSDKERR_NoError
#define LINKERR_NotInited					GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_NotInited)
#define LINKERR_InvalidArg					GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_InvalidArg)
#define LINKERR_InitFailed					GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_InitFailed)
#define LINKERR_NoMemory					GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_NoMemory)
#define LINKERR_Unsupported					GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_Unsupported)
#define LINKERR_HandleObjectInvalid			GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_HandleObjectInvalid)
#define LINKERR_CDSError					GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_CDSError)
#define LINKERR_Timeout						GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_Timeout)
#define LINKERR_CommunicationsError			GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_CommunicationsError)
#define LINKWARN_NotFound					GNSDKERR_MAKE_WARNING(GNSDKPKG_Link, GNSDKERR_NotFound)
#define LINKERR_NotFound					GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_NotFound)
#define LINKERR_HandleObjectWrongType		GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_HandleObjectWrongType)
#define LINKERR_InvalidInputObject			GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_InvalidInputObject)
#define LINKERR_InsufficientInputData		GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_InsufficientInputData)
#define LINKERR_IncorrectUsage				GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_IncorrectUsage)
#define LINKERR_DataEncodeError				GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_DataEncodeError)
#define LINKERR_CompressionError			GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_CompressionError)
#define LINKERR_EncryptionError				GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_EncryptionError)
#define LINKERR_LicenseDisallowed			GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_LicenseDisallowed)
#define LINKERR_LicenseExpired				GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_LicenseExpired)
#define LINKERR_LicenseTrialExpired			GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_LicenseTrialExpired)
#define LINKERR_Busy						GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_Busy)
#define LINKERR_InvalidClientID				GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_InvalidClientID)
#define LINKERR_InvalidUserID				GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_InvalidUserID)
#define LINKERR_QuotaExceeded				GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_QuotaExceeded)
#define LINKERR_LocaleNotSet				GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_LocaleNotSet)
#define LINKERR_Aborted						GNSDKERR_MAKE_ERROR(GNSDKPKG_Link, GNSDKERR_Aborted)
#define LINKWARN_Aborted					GNSDKERR_MAKE_WARNING(GNSDKPKG_Link, GNSDKERR_Aborted)

/* Errors returned from the VideoID SDK */
#define VIDERR_NoError						GNSDKERR_NoError
#define VIDERR_NotInited					GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_NotInited)
#define VIDERR_InvalidArg					GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_InvalidArg)
#define VIDERR_InvalidData					GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_InvalidData)
#define VIDERR_InitFailed					GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_InitFailed)
#define VIDERR_NoMemory						GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_NoMemory)
#define VIDERR_HandleObjectInvalid			GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_HandleObjectInvalid)
#define VIDERR_HandleObjectWrongType		GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_HandleObjectWrongType)
#define VIDERR_QueryError					GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_QueryError)
#define VIDERR_CDSError						GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_CDSError)
#define VIDERR_Timeout						GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_Timeout)
#define VIDERR_CommunicationsError			GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_CommunicationsError)
#define VIDERR_NotFound						GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_NotFound)
#define VIDWARN_NotFound					GNSDKERR_MAKE_WARNING(GNSDKPKG_VideoID, GNSDKERR_NotFound)
#define VIDERR_InvalidInputObject			GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_InvalidInputObject)
#define VIDERR_BadXMLFormat					GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_BadXMLFormat)
#define VIDERR_UnknownResponseCode			GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_UnknownResponseCode)
#define VIDERR_InvalidTOC					GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_InvalidTOC)
#define VIDERR_DataEncodeError				GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_DataEncodeError)
#define VIDERR_CompressionError				GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_CompressionError)
#define VIDERR_EncryptionError				GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_EncryptionError)
#define VIDERR_InsufficientInputData		GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_InsufficientInputData)
#define VIDERR_ClientError					GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_ClientError)
#define VIDERR_ServerError					GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_ServerError)
#define VIDERR_IckyError					GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_IckyError)
#define VIDERR_Unsupported					GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_Unsupported)
#define VIDERR_OutOfRange					GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_IndexOutOfRange)
#define VIDERR_LicenseDisallowed			GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_LicenseDisallowed)
#define VIDERR_LicenseExpired				GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_LicenseExpired)
#define VIDERR_LicenseTrialExpired			GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_LicenseTrialExpired)
#define VIDERR_Busy							GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_Busy)
#define VIDERR_InvalidClientID				GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_InvalidClientID)
#define VIDERR_InvalidUserID				GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_InvalidUserID)
#define VIDERR_InvalidTOCVerion				GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_UnknownVersion)
#define VIDERR_QuotaExceeded				GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_QuotaExceeded)
#define VIDERR_LocaleNotSet					GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_LocaleNotSet)
#define VIDERR_InvalidUTF8					GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_InvalidUTF8)
#define VIDERR_Aborted						GNSDKERR_MAKE_ERROR(GNSDKPKG_VideoID, GNSDKERR_Aborted)
#define VIDWARN_Aborted						GNSDKERR_MAKE_WARNING(GNSDKPKG_VideoID, GNSDKERR_Aborted)

/* Errors returned from the Submit SDK */
#define SUBMITERR_NoError					GNSDKERR_NoError
#define SUBMITERR_NotInited					GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_NotInited)
#define SUBMITERR_InvalidArg				GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_InvalidArg)
#define SUBMITERR_InitFailed				GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_InitFailed)
#define SUBMITERR_NoMemory					GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_NoMemory)
#define SUBMITERR_Unsupported				GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_Unsupported)
#define SUBMITERR_HandleObjectInvalid		GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_HandleObjectInvalid)
#define SUBMITERR_QueryError				GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_QueryError)
#define SUBMITERR_CommunicationsError		GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_CommunicationsError)
#define SUBMITERR_ClientError				GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_ClientError)
#define SUBMITERR_ServerError				GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_ServerError)
#define SUBMITERR_IckyError					GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_IckyError)
#define SUBMITERR_NotFound					GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_NotFound)
#define SUBMITWARN_NotFound					GNSDKERR_MAKE_WARNING(GNSDKPKG_Submit, GNSDKERR_NotFound)
#define SUBMITERR_HandleObjectWrongType		GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_HandleObjectWrongType)
#define SUBMITERR_InvalidInputObject		GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_InvalidInputObject)
#define SUBMITERR_InsufficientInputData		GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_InsufficientInputData)
#define SUBMITERR_IncorrectUsage			GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_IncorrectUsage)
#define SUBMITERR_DataEncodeError			GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_DataEncodeError)
#define SUBMITERR_CompressionError			GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_CompressionError)
#define SUBMITERR_EncryptionError			GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_EncryptionError)
#define SUBMITERR_LicenseDisallowed			GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_LicenseDisallowed)
#define SUBMITERR_LicenseExpired			GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_LicenseExpired)
#define SUBMITERR_LicenseTrialExpired		GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_LicenseTrialExpired)
#define SUBMITERR_Busy						GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_Busy)
#define SUBMITERR_InvalidClientID			GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_InvalidClientID)
#define SUBMITERR_InvalidUserID				GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_InvalidUserID)
#define SUBMITERR_QuotaExceeded				GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_QuotaExceeded)
#define SUBMITERR_MissingField				GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_MissingField)
#define SUBMITERR_InvalidContents			GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_InvalidContents)
#define SUBMITWARN_NotEditable				GNSDKERR_MAKE_WARNING(GNSDKPKG_Submit, GNSDKERR_NotEditable)
#define SUBMITERR_NotEditable				GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_NotEditable)
#define SUBMITERR_InvalidTOC				GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_InvalidTOC)
#define SUBMITERR_OutOfRange				GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_IndexOutOfRange)
#define SUBMITERR_LibraryNotLoaded			GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_LibraryNotLoaded)
#define SUBMITERR_TooMany					GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_TooMany)
#define SUBMITERR_Insufficient				GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_InsufficientInputData)
#define SUBMITERR_Aborted					GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_Aborted)
#define SUBMITWARN_Aborted					GNSDKERR_MAKE_WARNING(GNSDKPKG_Submit, GNSDKERR_Aborted)
#define SUBMITERR_Timeout					GNSDKERR_MAKE_ERROR(GNSDKPKG_Submit, GNSDKERR_Timeout)
#define SUBMITWARN_SilentAudio				GNSDKERR_MAKE_WARNING(GNSDKPKG_Submit, GNSDKERR_SilentAudio)

/* Errors returned from SQLite SDK */
#define SQLITEERR_NoError					GNSDKERR_NoError
#define SQLITEERR_NoMemory					GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_SQLite, GNSDKERR_NoMemory)
#define SQLITEERR_InitFailed				GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_SQLite, GNSDKERR_InitFailed)
#define SQLITEERR_NotInited					GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_SQLite, GNSDKERR_NotInited)
#define SQLITEERR_NotFound					GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_SQLite, GNSDKERR_NotFound)
#define SQLITEWARN_NotFound					GNSDKERR_MAKE_WARNING(GNSDKPKG_Storage_SQLite, GNSDKERR_NotFound)
#define SQLITEERR_Busy						GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_SQLite, GNSDKERR_Busy)
#define SQLITEERR_HandleObjectInvalid		GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_SQLite, GNSDKERR_HandleObjectInvalid)
#define SQLITEERR_HandleObjectWrongType		GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_SQLite, GNSDKERR_HandleObjectWrongType)
#define SQLITEERR_InvalidArg				GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_SQLite, GNSDKERR_InvalidArg)
#define SQLITEERR_LocalDatabaseNotFound		GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_SQLite, GNSDKERR_LocalDatabaseNotFound)
#define SQLITEWARN_LocalDatabaseNotFound	GNSDKERR_MAKE_WARNING(GNSDKPKG_Storage_SQLite, GNSDKERR_LocalDatabaseNotFound)
#define SQLITEERR_InvalidStorageLocation	GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_SQLite, GNSDKERR_FileInvalidFolder)
#define SQLITEERR_InvalidSchema				GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_SQLite, GNSDKERR_InvalidSchema)
#define SQLITEERR_SchemaMismatch			GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_SQLite, GNSDKERR_SchemaMismatch)
#define SQLITEERR_StatementError			GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_SQLite, GNSDKERR_InvalidFormat)
#define SQLITEERR_EndOfRecords				GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_SQLite, GNSDKERR_EndOfRecords)
#define SQLITEWARN_EndOfRecords				GNSDKERR_MAKE_WARNING(GNSDKPKG_Storage_SQLite, GNSDKERR_EndOfRecords)
#define SQLITEERR_DuplicateRecord			GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_SQLite, GNSDKERR_DuplicateRecord)
#define SQLITEWARN_DuplicateRecord			GNSDKERR_MAKE_WARNING(GNSDKPKG_Storage_SQLite, GNSDKERR_DuplicateRecord)
#define SQLITEERR_StorageFull				GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_SQLite, GNSDKERR_FileTooLarge)
#define SQLITEWARN_StorageFull				GNSDKERR_MAKE_WARNING(GNSDKPKG_Storage_SQLite, GNSDKERR_FileTooLarge)
#define SQLITEERR_ReadOnly					GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_SQLite, GNSDKERR_ReadOnly)
#define SQLITEERR_IOError					GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_SQLite, GNSDKERR_IOError)
#define SQLITEERR_CorruptDB					GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_SQLite, GNSDKERR_CorruptDB)
#define SQLITEERR_Unknown					GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_SQLite, GNSDKERR_Unknown)
#define SQLITEERR_IncorrectUsage			GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_SQLite, GNSDKERR_IncorrectUsage)
#define SQLITEERR_Unsupported				GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_SQLite, GNSDKERR_Unsupported)


/* Errors returned from DSP SDK */
#define DSPERR_NoError						GNSDKERR_NoError
#define DSPERR_NoMemory						GNSDKERR_MAKE_ERROR(GNSDKPKG_DSP, GNSDKERR_NoMemory)
#define DSPERR_InitFailed					GNSDKERR_MAKE_ERROR(GNSDKPKG_DSP, GNSDKERR_InitFailed)
#define DSPERR_NotInited					GNSDKERR_MAKE_ERROR(GNSDKPKG_DSP, GNSDKERR_NotInited)
#define DSPERR_NotFound						GNSDKERR_MAKE_ERROR(GNSDKPKG_DSP, GNSDKERR_NotFound)
#define DSPWARN_NotFound					GNSDKERR_MAKE_WARNING(GNSDKPKG_DSP, GNSDKERR_NotFound)
#define DSPERR_Busy							GNSDKERR_MAKE_ERROR(GNSDKPKG_DSP, GNSDKERR_Busy)
#define DSPERR_HandleObjectInvalid			GNSDKERR_MAKE_ERROR(GNSDKPKG_DSP, GNSDKERR_HandleObjectInvalid)
#define DSPERR_HandleObjectWrongType		GNSDKERR_MAKE_ERROR(GNSDKPKG_DSP, GNSDKERR_HandleObjectWrongType)
#define DSPERR_InvalidArg					GNSDKERR_MAKE_ERROR(GNSDKPKG_DSP, GNSDKERR_InvalidArg)
#define DSPERR_Unknown						GNSDKERR_MAKE_ERROR(GNSDKPKG_DSP, GNSDKERR_Unknown)
#define DSPERR_Unsupported					GNSDKERR_MAKE_ERROR(GNSDKPKG_DSP, GNSDKERR_Unsupported)
#define DSPERR_IckyError					GNSDKERR_MAKE_ERROR(GNSDKPKG_DSP, GNSDKERR_IckyError)
#define DSPWARN_InsufficientInputData		GNSDKERR_MAKE_WARNING(GNSDKPKG_DSP, GNSDKERR_InsufficientInputData)
#define DSPERR_LicenseInvalid				GNSDKERR_MAKE_ERROR(GNSDKPKG_DSP, GNSDKERR_LicenseInvalid)
#define DSPERR_LicenseDisallowed			GNSDKERR_MAKE_ERROR(GNSDKPKG_DSP, GNSDKERR_LicenseDisallowed)
#define DSPERR_LicenseExpired				GNSDKERR_MAKE_ERROR(GNSDKPKG_DSP, GNSDKERR_LicenseExpired)
#define DSPERR_LicenseTrialExpired			GNSDKERR_MAKE_ERROR(GNSDKPKG_DSP, GNSDKERR_LicenseTrialExpired)


/* Errors returned from FP SDK */
#define FPERR_NoError						GNSDKERR_NoError
#define FPERR_NoMemory						GNSDKERR_MAKE_ERROR(GNSDKPKG_FP, GNSDKERR_NoMemory)
#define FPERR_InitFailed					GNSDKERR_MAKE_ERROR(GNSDKPKG_FP, GNSDKERR_InitFailed)
#define FPERR_NotInited						GNSDKERR_MAKE_ERROR(GNSDKPKG_FP, GNSDKERR_NotInited)
#define FPERR_NotFound						GNSDKERR_MAKE_ERROR(GNSDKPKG_FP, GNSDKERR_NotFound)
#define FPWARN_NotFound						GNSDKERR_MAKE_WARNING(GNSDKPKG_FP, GNSDKERR_NotFound)
#define FPERR_Busy							GNSDKERR_MAKE_ERROR(GNSDKPKG_FP, GNSDKERR_Busy)
#define FPERR_HandleObjectInvalid			GNSDKERR_MAKE_ERROR(GNSDKPKG_FP, GNSDKERR_HandleObjectInvalid)
#define FPERR_HandleObjectWrongType			GNSDKERR_MAKE_ERROR(GNSDKPKG_FP, GNSDKERR_HandleObjectWrongType)
#define FPERR_InvalidArg					GNSDKERR_MAKE_ERROR(GNSDKPKG_FP, GNSDKERR_InvalidArg)
#define FPERR_Unknown						GNSDKERR_MAKE_ERROR(GNSDKPKG_FP, GNSDKERR_Unknown)
#define FPERR_Unsupported					GNSDKERR_MAKE_ERROR(GNSDKPKG_FP, GNSDKERR_Unsupported)
#define FPERR_IckyError						GNSDKERR_MAKE_ERROR(GNSDKPKG_FP, GNSDKERR_IckyError)
#define FPERR_IncorrectUsage				GNSDKERR_MAKE_ERROR(GNSDKPKG_FP, GNSDKERR_IncorrectUsage)
#define FPWARN_InsufficientInputData		GNSDKERR_MAKE_WARNING(GNSDKPKG_FP, GNSDKERR_InsufficientInputData)
#define FPWARN_LocalDatabaseNotFound		GNSDKERR_MAKE_WARNING(GNSDKPKG_FP, GNSDKERR_LocalDatabaseNotFound)
#define FPERR_LocalDBSchemaMismatch			GNSDKERR_MAKE_ERROR(GNSDKPKG_FP, GNSDKERR_SchemaMismatch)
#define FPWARN_SilentAudio					GNSDKERR_MAKE_WARNING(GNSDKPKG_FP, GNSDKERR_SilentAudio)

/* Errors returned from the Playlist SDK */
#define PLERR_NoError						GNSDKERR_NoError
#define PLERR_NotInited						GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_NotInited)
#define PLERR_InvalidArg					GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_InvalidArg)
#define PLERR_InitFailed					GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_InitFailed)
#define PLERR_NoMemory						GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_NoMemory)
#define PLERR_Unsupported					GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_Unsupported)
#define PLERR_HandleObjectInvalid			GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_HandleObjectInvalid)
#define PLERR_HandleObjectWrongType			GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_HandleObjectWrongType)
#define PLERR_QueryError					GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_QueryError)
#define PLERR_Timeout						GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_Timeout)
#define PLERR_CommunicationsError			GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_CommunicationsError)
#define PLERR_NotFound						GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_NotFound)
#define PLWARN_NotFound						GNSDKERR_MAKE_WARNING(GNSDKPKG_Playlist, GNSDKERR_NotFound)
#define PLERR_DataEncodeError				GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_DataEncodeError)
#define PLERR_CompressionError				GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_CompressionError)
#define PLERR_EncryptionError				GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_EncryptionError)
#define PLERR_InsufficientInputData			GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_InsufficientInputData)
#define PLERR_LicenseDisallowed				GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_LicenseDisallowed)
#define PLERR_LicenseExpired				GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_LicenseExpired)
#define PLERR_LicenseTrialExpired			GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_LicenseTrialExpired)
#define PLERR_QuotaExceeded					GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_QuotaExceeded)
#define PLERR_LibraryNotLoaded				GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_LibraryNotLoaded)
#define PLERR_LocaleNotSet					GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_LocaleNotSet)
#define PLERR_InvalidUTF8					GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_InvalidUTF8)
#define PLERR_InvalidData					GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_InvalidData)
#define PLERR_InvalidSchema					GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_InvalidSchema)
#define PLERR_InvalidCall					GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_InvalidCall)
#define PLERR_OutOfRange					GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_IndexOutOfRange)
#define PLWARN_OutOfRange					GNSDKERR_MAKE_WARNING(GNSDKPKG_Playlist, GNSDKERR_IndexOutOfRange)
#define PLERR_Unexpected					GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_Unexpected)
#define PLERR_BufferTooSmall				GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_BufferTooSmall)
#define PLERR_SeedRequired					GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_SeedRequired)
#define PLERR_Aborted						GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_Aborted)
#define PLWARN_Aborted						GNSDKERR_MAKE_WARNING(GNSDKPKG_Playlist, GNSDKERR_Aborted)
#define PLERR_StatementError				GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_StatementError)
#define PLERR_UnexpectedEndOfInput			GNSDKERR_MAKE_ERROR(GNSDKPKG_Playlist, GNSDKERR_UnexpectedEndOfInput)


/* Errors returned from the Helper SDK */
#define HELPERERR_NoError					GNSDKERR_NoError
#define HELPERERR_NotInited					GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_NotInited)
#define HELPERERR_InvalidArg				GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_InvalidArg)
#define HELPERERR_InitFailed				GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_InitFailed)
#define HELPERERR_NoMemory					GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_NoMemory)
#define HELPERERR_Unsupported				GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_Unsupported)
#define HELPERERR_HandleObjectInvalid		GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_HandleObjectInvalid)
#define HELPERERR_HandleObjectWrongType		GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_HandleObjectWrongType)
#define HELPERERR_QueryError				GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_QueryError)
#define HELPERERR_CDSError					GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_CDSError)
#define HELPERERR_CommunicationsError		GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_CommunicationsError)
#define HELPERERR_NotFound					GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_NotFound)
#define HELPERWARN_NotFound					GNSDKERR_MAKE_WARNING(GNSDKPKG_Helper, GNSDKERR_NotFound)
#define HELPERERR_OutOfRange				GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_IndexOutOfRange)
#define HELPERERR_InvalidInputObject		GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_InvalidInputObject)
#define HELPERERR_UnknownResponseCode		GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_UnknownResponseCode)
#define HELPERERR_DataEncodeError			GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_DataEncodeError)
#define HELPERERR_CompressionError			GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_CompressionError)
#define HELPERERR_EncryptionError			GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_EncryptionError)
#define HELPERERR_InsufficientInputData		GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_InsufficientInputData)
#define HELPERERR_LicenseDisallowed			GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_LicenseDisallowed)
#define HELPERERR_LicenseExpired			GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_LicenseExpired)
#define HELPERERR_LicenseTrialExpired		GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_LicenseTrialExpired)
#define HELPERERR_Busy						GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_Busy)
#define HELPERERR_InvalidClientID			GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_InvalidClientID)
#define HELPERERR_InvalidUserID				GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_InvalidUserID)
#define HELPERERR_QuotaExceeded				GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_QuotaExceeded)
#define HELPERERR_LibraryNotLoaded			GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_LibraryNotLoaded)
#define HELPERERR_LocaleNotSet				GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_LocaleNotSet)
#define HELPERERR_InvalidUTF8				GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_InvalidUTF8)
#define HELPERERR_InvalidData				GNSDKERR_MAKE_ERROR(GNSDKPKG_Helper, GNSDKERR_InvalidData)


#define MIDMERR_NoError						GNSDKERR_NoError
#define MIDMERR_NotInited					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_NotInited)
#define MIDMERR_InvalidArg					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_InvalidArg)
#define MIDMERR_InitFailed					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_InitFailed)
#define MIDMERR_NoMemory					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_NoMemory)
#define MIDMERR_Unsupported					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_Unsupported)
#define MIDMERR_HandleObjectInvalid			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_HandleObjectInvalid)
#define MIDMERR_HandleObjectWrongType		GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_HandleObjectWrongType)
#define MIDMERR_QueryError					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_QueryError)
#define MIDMERR_Aborted						GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_Aborted)
#define MIDMWARN_Aborted					GNSDKERR_MAKE_WARNING(GNSDKPKG_MusicID_Match, GNSDKERR_Aborted)
#define MIDMERR_Timeout						GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_Timeout)
#define MIDMERR_CommunicationsError			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_CommunicationsError)
#define MIDMERR_NotFound					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_NotFound)
#define MIDMWARN_NotFound					GNSDKERR_MAKE_WARNING(GNSDKPKG_MusicID_Match, GNSDKERR_NotFound)
#define MIDMERR_NotProcessed				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_Unexpected)
#define MIDMERR_Busy						GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_Busy)
#define MIDMERR_InvalidInputObject			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_InvalidInputObject)
#define MIDMERR_DataEncodeError				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_DataEncodeError)
#define MIDMERR_CompressionError			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_CompressionError)
#define MIDMERR_EncryptionError				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_EncryptionError)
#define MIDMERR_InsufficientInputData		GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_InsufficientInputData)
#define MIDMERR_LicenseDisallowed			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_LicenseDisallowed)
#define MIDMERR_LicenseExpired				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_LicenseExpired)
#define MIDMERR_LicenseTrialExpired			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_LicenseTrialExpired)
#define MIDMERR_InvalidClientID				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_InvalidClientID)
#define MIDMERR_InvalidUserID				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_InvalidUserID)
#define MIDMERR_QuotaExceeded				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_QuotaExceeded)
#define MIDMERR_LibraryNotLoaded			GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_LibraryNotLoaded)
#define MIDMERR_LocaleNotSet				GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_LocaleNotSet)
#define MIDMERR_InvalidUTF8					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_InvalidUTF8)
#define MIDMERR_InvalidData					GNSDKERR_MAKE_ERROR(GNSDKPKG_MusicID_Match, GNSDKERR_InvalidData)

/* Errors returned from GDB SDK */
#define GDBERR_NoError                      GNSDKERR_NoError
#define GDBERR_NoMemory                     GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_GDB, GNSDKERR_NoMemory)
#define GDBERR_InitFailed                   GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_GDB, GNSDKERR_InitFailed)
#define GDBERR_NotInited                    GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_GDB, GNSDKERR_NotInited)
#define GDBERR_Unsupported					GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_GDB, GNSDKERR_Unsupported)
#define GDBERR_NotFound                     GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_GDB, GNSDKERR_NotFound)
#define GDBWARN_NotFound                    GNSDKERR_MAKE_WARNING(GNSDKPKG_Storage_GDB, GNSDKERR_NotFound)
#define GDBERR_Busy                         GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_GDB, GNSDKERR_Busy)
#define GDBERR_HandleObjectInvalid          GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_GDB, GNSDKERR_HandleObjectInvalid)
#define GDBERR_InvalidArg                   GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_GDB, GNSDKERR_InvalidArg)
#define GDBERR_InvalidStorageLocation       GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_GDB, GNSDKERR_FileInvalidFolder)
#define GDBERR_InvalidSchema                GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_GDB, GNSDKERR_InvalidSchema)
#define GDBERR_SchemaMismatch               GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_GDB, GNSDKERR_SchemaMismatch)
#define GDBERR_StatementError               GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_GDB, GNSDKERR_InvalidFormat)
#define GDBERR_EndOfRecords                 GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_GDB, GNSDKERR_EndOfRecords)
#define GDBWARN_EndOfRecords                GNSDKERR_MAKE_WARNING(GNSDKPKG_Storage_GDB, GNSDKERR_EndOfRecords)
#define GDBERR_DuplicateRecord              GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_GDB, GNSDKERR_DuplicateRecord)
#define GDBWARN_DuplicateRecord             GNSDKERR_MAKE_WARNING(GNSDKPKG_Storage_GDB, GNSDKERR_DuplicateRecord)
#define GDBERR_StorageFull                  GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_GDB, GNSDKERR_FileTooLarge)
#define GDBWARN_StorageFull                 GNSDKERR_MAKE_WARNING(GNSDKPKG_Storage_GDB, GNSDKERR_FileTooLarge)
#define GDBERR_InvalidRecord                GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_GDB, GNSDKERR_InvalidRecord)
#define GDBERR_InvalidStorage				GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_GDB, GNSDKERR_InvalidStorage)
#define GDBERR_InvalidIterator				GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_GDB, GNSDKERR_InvalidIterator)
#define GDBERR_Unknown						GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_GDB, GNSDKERR_Unknown)

/* Errors returned from ACR SDK */
#define ACRERR_NoError						GNSDKERR_NoError
#define ACRERR_NoMemory						GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_NoMemory)
#define ACRERR_InvalidArg					GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_InvalidArg)
#define ACRERR_InitFailed					GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_InitFailed)
#define ACRERR_NotInited					GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_NotInited)
#define ACRERR_NotFound						GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_NotFound)
#define ACRWARN_NotFound					GNSDKERR_MAKE_WARNING(GNSDKPKG_ACR, GNSDKERR_NotFound)
#define ACRERR_HandleObjectWrongType		GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_HandleObjectWrongType)
#define ACRERR_Unsupported					GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_Unsupported)
#define ACRERR_HandleObjectInvalid			GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_HandleObjectInvalid)
#define ACRERR_OutOfRange					GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_IndexOutOfRange)
#define ACRERR_Busy							GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_Busy)
#define ACRERR_Timeout						GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_Timeout)
#define ACRERR_LicenseDisallowed			GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_LicenseDisallowed)
#define ACRERR_LicenseExpired				GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_LicenseExpired)
#define ACRERR_LicenseTrialExpired			GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_LicenseTrialExpired)
#define ACRWARN_TemporalDiscontinuity		GNSDKERR_MAKE_WARNING(GNSDKPKG_ACR, GNSDKERR_TemporalDiscontinuity)
#define ACRERR_InvalidClientID				GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_InvalidClientID)
#define ACRERR_InvalidUserID				GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_InvalidUserID)
#define ACRERR_QuotaExceeded				GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_QuotaExceeded)
#define ACRERR_LibraryNotLoaded				GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_LibraryNotLoaded)
#define ACRERR_IncorrectUsage				GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_IncorrectUsage)
#define ACRERR_MissingListingData			GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_MissingListingData)
#define ACRERR_ListUpdateNeeded				GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_ListUpdateNeeded)
#define ACRERR_Aborted						GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_Aborted)
#define ACRWARN_Aborted					    GNSDKERR_MAKE_WARNING(GNSDKPKG_ACR, GNSDKERR_Aborted)
#define ACRERR_InvalidData					GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_InvalidData)
#define ACRERR_UnsupportedAlg				GNSDKERR_MAKE_ERROR(GNSDKPKG_ACR, GNSDKERR_UnsupportedAlg)

/* Errors returned from ASTREAM SDK */
#define ASTREAMERR_NoError						GNSDKERR_NoError
#define ASTREAMERR_NoMemory						GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_NoMemory)
#define ASTREAMERR_InvalidArg					GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_InvalidArg)
#define ASTREAMERR_InitFailed					GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_InitFailed)
#define ASTREAMERR_NotInited					GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_NotInited)
#define ASTREAMERR_NotFound						GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_NotFound)
#define ASTREAMWARN_NotFound					GNSDKERR_MAKE_WARNING(GNSDKPKG_ASTREAM, GNSDKERR_NotFound)
#define ASTREAMERR_HandleObjectWrongType		GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_HandleObjectWrongType)
#define ASTREAMERR_Unsupported					GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_Unsupported)
#define ASTREAMERR_HandleObjectInvalid			GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_HandleObjectInvalid)
#define ASTREAMERR_OutOfRange					GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_IndexOutOfRange)
#define ASTREAMERR_Busy							GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_Busy)
#define ASTREAMERR_Timeout						GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_Timeout)
#define ASTREAMERR_LicenseDisallowed			GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_LicenseDisallowed)
#define ASTREAMERR_LicenseExpired				GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_LicenseExpired)
#define ASTREAMERR_LicenseTrialExpired			GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_LicenseTrialExpired)
#define ASTREAMWARN_TemporalDiscontinuity		GNSDKERR_MAKE_WARNING(GNSDKPKG_ASTREAM, GNSDKERR_TemporalDiscontinuity)
#define ASTREAMERR_InvalidClientID				GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_InvalidClientID)
#define ASTREAMERR_InvalidUserID				GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_InvalidUserID)
#define ASTREAMERR_QuotaExceeded				GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_QuotaExceeded)
#define ASTREAMERR_LibraryNotLoaded				GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_LibraryNotLoaded)
#define ASTREAMERR_IncorrectUsage				GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_IncorrectUsage)
#define ASTREAMERR_MissingListingData			GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_MissingListingData)
#define ASTREAMERR_ListUpdateNeeded				GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_ListUpdateNeeded)
#define ASTREAMERR_Aborted						GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_Aborted)
#define ASTREAMWARN_Aborted					    GNSDKERR_MAKE_WARNING(GNSDKPKG_ASTREAM, GNSDKERR_Aborted)
#define ASTREAMERR_InvalidData					GNSDKERR_MAKE_ERROR(GNSDKPKG_ASTREAM, GNSDKERR_InvalidData)

/* Errors returned from BUNDLE SDK */
#define BUNDLEERR_NoError						GNSDKERR_NoError
#define BUNDLEERR_NoMemory						GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_NoMemory)
#define BUNDLEERR_InvalidArg					GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_InvalidArg)
#define BUNDLEERR_InitFailed					GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_InitFailed)
#define BUNDLEERR_NotInited					GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_NotInited)
#define BUNDLEERR_NotFound						GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_NotFound)
#define BUNDLEWARN_NotFound					GNSDKERR_MAKE_WARNING(GNSDKPKG_BUNDLE, GNSDKERR_NotFound)
#define BUNDLEERR_HandleObjectWrongType		GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_HandleObjectWrongType)
#define BUNDLEERR_Unsupported					GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_Unsupported)
#define BUNDLEERR_HandleObjectInvalid			GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_HandleObjectInvalid)
#define BUNDLEERR_OutOfRange					GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_IndexOutOfRange)
#define BUNDLEERR_Busy							GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_Busy)
#define BUNDLEERR_Timeout						GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_Timeout)
#define BUNDLEERR_LicenseDisallowed			GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_LicenseDisallowed)
#define BUNDLEERR_LicenseExpired				GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_LicenseExpired)
#define BUNDLEERR_LicenseTrialExpired			GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_LicenseTrialExpired)
#define BUNDLEWARN_TemporalDiscontinuity		GNSDKERR_MAKE_WARNING(GNSDKPKG_BUNDLE, GNSDKERR_TemporalDiscontinuity)
#define BUNDLEERR_InvalidClientID				GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_InvalidClientID)
#define BUNDLEERR_InvalidUserID				GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_InvalidUserID)
#define BUNDLEERR_QuotaExceeded				GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_QuotaExceeded)
#define BUNDLEERR_LibraryNotLoaded				GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_LibraryNotLoaded)
#define BUNDLEERR_IncorrectUsage				GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_IncorrectUsage)
#define BUNDLEERR_MissingListingData			GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_MissingListingData)
#define BUNDLEERR_ListUpdateNeeded				GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_ListUpdateNeeded)
#define BUNDLEERR_Aborted						GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_Aborted)
#define BUNDLEWARN_Aborted					    GNSDKERR_MAKE_WARNING(GNSDKPKG_BUNDLE, GNSDKERR_Aborted)
#define BUNDLEERR_InvalidData					GNSDKERR_MAKE_ERROR(GNSDKPKG_BUNDLE, GNSDKERR_InvalidData)




/* Errors returned from EPG SDK */
#define EPGERR_NoError						GNSDKERR_NoError
#define EPGERR_NotInited					GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_NotInited)
#define EPGERR_InvalidArg					GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_InvalidArg)
#define EPGERR_InvalidData					GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_InvalidData)
#define EPGERR_InitFailed					GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_InitFailed)
#define EPGERR_NoMemory						GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_NoMemory)
#define EPGERR_HandleObjectInvalid			GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_HandleObjectInvalid)
#define EPGERR_HandleObjectWrongType		GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_HandleObjectWrongType)
#define EPGERR_QueryError					GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_QueryError)
#define EPGERR_CDSError						GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_CDSError)
#define EPGERR_CommunicationsError			GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_CommunicationsError)
#define EPGERR_NotFound						GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_NotFound)
#define EPGWARN_NotFound					GNSDKERR_MAKE_WARNING(GNSDKPKG_EPG, GNSDKERR_NotFound)
#define EPGERR_InvalidInputObject			GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_InvalidInputObject)
#define EPGERR_BadXMLFormat					GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_BadXMLFormat)
#define EPGERR_UnknownResponseCode			GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_UnknownResponseCode)
#define EPGERR_InvalidTOC					GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_InvalidTOC)
#define EPGERR_DataEncodeError				GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_DataEncodeError)
#define EPGERR_CompressionError				GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_CompressionError)
#define EPGERR_EncryptionError				GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_EncryptionError)
#define EPGERR_InsufficientInputData		GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_InsufficientInputData)
#define EPGERR_ClientError					GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_ClientError)
#define EPGERR_ServerError					GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_ServerError)
#define EPGERR_IckyError					GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_IckyError)
#define EPGERR_Unsupported					GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_Unsupported)
#define EPGERR_OutOfRange					GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_IndexOutOfRange)
#define EPGERR_LicenseDisallowed			GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_LicenseDisallowed)
#define EPGERR_LicenseExpired				GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_LicenseExpired)
#define EPGERR_LicenseTrialExpired			GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_LicenseTrialExpired)
#define EPGERR_Busy							GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_Busy)
#define EPGERR_InvalidClientID				GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_InvalidClientID)
#define EPGERR_InvalidUserID				GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_InvalidUserID)
#define EPGERR_InvalidTOCVerion				GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_UnknownVersion)
#define EPGERR_QuotaExceeded				GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_QuotaExceeded)
#define EPGERR_LocaleNotSet					GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_LocaleNotSet)
#define EPGERR_InvalidUTF8					GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_InvalidUTF8)
#define EPGERR_Disconnected					GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_Disconnected)
#define EPGERR_TimeOut						GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_Timeout)
#define EPGERR_Unsupported					GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_Unsupported)
#define EPGERR_IncorrectUsage				GNSDKERR_MAKE_ERROR(GNSDKPKG_EPG, GNSDKERR_IncorrectUsage)

#define LCLERR_NoError						GNSDKERR_NoError
#define LCLERR_NoMemory						GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_NoMemory)
#define LCLERR_InvalidArg					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_InvalidArg)
#define LCLERR_InitFailed					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_InitFailed)
#define LCLERR_NotInited					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_NotInited)
#define LCLERR_NotFound						GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_NotFound)
#define LCLWARN_NotFound					GNSDKERR_MAKE_WARNING(GNSDKPKG_Lookup_Local, GNSDKERR_NotFound)
#define LCLERR_HandleObjectWrongType		GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_HandleObjectWrongType)
#define LCLERR_Unsupported					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_Unsupported)
#define LCLERR_HandleObjectInvalid			GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_HandleObjectInvalid)
#define LCLERR_InvalidClientID				GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_InvalidClientID)
#define LCLERR_InvalidUserID				GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_InvalidUserID)
#define LCLERR_QuotaExceeded				GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_QuotaExceeded)
#define LCLERR_IncorrectUsage				GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_IncorrectUsage)
#define LCLERR_InvalidTOC					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_InvalidTOC)
#define LCLERR_QueryError					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_QueryError)
#define LCLERR_CDSError						GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_CDSError)
#define LCLERR_DataEncodeError				GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_DataEncodeError)
#define LCLERR_CompressionError				GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_CompressionError)
#define LCLERR_EncryptionError				GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_EncryptionError)
#define LCLERR_InvalidFormat				GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_InvalidFormat)
#define LCLERR_InsufficientInput			GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_InsufficientInputData)
#define LCLERR_FileNotFound					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_FileNotFound)
#define	LCLERR_HashingError					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_HashingError)
#define LCLERR_InvalidUserID				GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_InvalidUserID)
#define LCLWARN_LocaleNotSet				GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_LocaleNotSet)
#define LCLWARN_LocalDatabaseNotFound		GNSDKERR_MAKE_WARNING(GNSDKPKG_Lookup_Local, GNSDKERR_LocalDatabaseNotFound)
#define LCLERR_LocalDBSchemaMismatch		GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_SchemaMismatch)
#define LCLERR_LocalDatabaseNotEnabled		GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_Local, GNSDKERR_LocalDatabaseNotEnabled)
#define LCLWARN_LocalDatabaseNotEnabled		GNSDKERR_MAKE_WARNING(GNSDKPKG_Lookup_Local, GNSDKERR_LocalDatabaseNotEnabled)
#define LCLERR_LocalDatabaseLocationNotSet	GNSDKERR_MAKE_WARNING(GNSDKPKG_Lookup_Local, GNSDKERR_LocalDatabaseLocationNotSet)

#define EDBERR_NoError						GNSDKERR_NoError
#define EDBERR_NotInited					GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_NotInited)
#define EDBERR_InvalidArg					GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_InvalidArg)
#define EDBERR_InitFailed					GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_InitFailed)
#define EDBERR_NoMemory						GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_NoMemory)
#define EDBERR_Unsupported					GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_Unsupported)
#define EDBERR_HandleObjectInvalid			GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_HandleObjectInvalid)
#define EDBERR_HandleObjectWrongType		GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_HandleObjectWrongType)
#define EDBERR_QueryError					GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_QueryError)
#define EDBERR_CommunicationsError			GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_CommunicationsError)
#define EDBERR_NotFound						GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_NotFound)
#define EDBWARN_NotFound					GNSDKERR_MAKE_WARNING(GNSDKPKG_EDBInstall, GNSDKERR_NotFound)
#define EDBERR_NotProcessed					GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_Unexpected)
#define EDBERR_Busy							GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_Busy)
#define EDBERR_InvalidInputObject			GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_InvalidInputObject)
#define EDBERR_DataEncodeError				GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_DataEncodeError)
#define EDBERR_CompressionError				GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_CompressionError)
#define EDBERR_EncryptionError				GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_EncryptionError)
#define EDBERR_InsufficientInputData		GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_InsufficientInputData)
#define EDBERR_LicenseDisallowed			GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_LicenseDisallowed)
#define EDBERR_LicenseExpired				GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_LicenseExpired)
#define EDBERR_LicenseTrialExpired			GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_LicenseTrialExpired)
#define EDBERR_InvalidClientID				GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_InvalidClientID)
#define EDBERR_InvalidUserID				GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_InvalidUserID)
#define EDBERR_QuotaExceeded				GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_QuotaExceeded)
#define EDBERR_LibraryNotLoaded				GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_LibraryNotLoaded)
#define EDBERR_LocaleNotSet					GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_LocaleNotSet)
#define EDBERR_InvalidUTF8					GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_InvalidUTF8)
#define EDBERR_InvalidData					GNSDKERR_MAKE_ERROR(GNSDKPKG_EDBInstall, GNSDKERR_InvalidData)


/* MoodGrid Errors*/
#define MGERR_NoError						GNSDKERR_NoError
#define MGERR_NotInited						GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_NotInited)
#define MGERR_InvalidArg					GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_InvalidArg)
#define MGERR_InitFailed					GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_InitFailed)
#define MGERR_NoMemory						GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_NoMemory)
#define MGERR_Unsupported					GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_Unsupported)
#define MGERR_HandleObjectInvalid			GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_HandleObjectInvalid)
#define MGERR_HandleObjectWrongType			GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_HandleObjectWrongType)
#define MGERR_QueryError					GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_QueryError)
#define MGERR_CommunicationsError			GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_CommunicationsError)
#define MGERR_NotFound						GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_NotFound)
#define MGWARN_NotFound						GNSDKERR_MAKE_WARNING(GNSDKPKG_MoodGrid, GNSDKERR_NotFound)
#define MGERR_Busy							GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_Busy)
#define MGERR_DataEncodeError				GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_DataEncodeError)
#define MGERR_CompressionError				GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_CompressionError)
#define MGERR_EncryptionError				GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_EncryptionError)
#define MGERR_InsufficientInputData			GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_InsufficientInputData)
#define MGERR_LicenseDisallowed				GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_LicenseDisallowed)
#define MGERR_LicenseExpired				GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_LicenseExpired)
#define MGERR_LicenseTrialExpired			GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_LicenseTrialExpired)
#define MGERR_QuotaExceeded					GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_QuotaExceeded)
#define MGERR_LibraryNotLoaded				GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_LibraryNotLoaded)
#define MGERR_LocaleNotSet					GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_LocaleNotSet)
#define MGERR_InvalidUTF8					GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_InvalidUTF8)
#define MGERR_InvalidData					GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_InvalidData)
#define MGERR_InvalidSchema					GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_InvalidSchema)
#define MGERR_InvalidCall					GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_InvalidCall)
#define MGERR_OutOfRange					GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_IndexOutOfRange)
#define MGWARN_OutOfRange					GNSDKERR_MAKE_WARNING(GNSDKPKG_MoodGrid, GNSDKERR_IndexOutOfRange)
#define MGERR_Unexpected					GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_Unexpected)
#define MGERR_BufferTooSmall				GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_BufferTooSmall)
#define MGERR_StatementError				GNSDKERR_MAKE_ERROR(GNSDKPKG_MoodGrid, GNSDKERR_StatementError)


/* Errors returned from QNX QDB SDK */
#define QNXSTGERR_NoError					GNSDKERR_NoError
#define QNXSTGERR_NoMemory					GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_QNX, GNSDKERR_NoMemory)
#define QNXSTGERR_InitFailed				GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_QNX, GNSDKERR_InitFailed)
#define QNXSTGERR_NotInited					GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_QNX, GNSDKERR_NotInited)
#define QNXSTGERR_NotFound					GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_QNX, GNSDKERR_NotFound)
#define QNXSTGWARN_NotFound					GNSDKERR_MAKE_WARNING(GNSDKPKG_Storage_QNX, GNSDKERR_NotFound)
#define QNXSTGERR_Busy						GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_QNX, GNSDKERR_Busy)
#define QNXSTGERR_HandleObjectInvalid		GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_QNX, GNSDKERR_HandleObjectInvalid)
#define QNXSTGERR_InvalidArg				GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_QNX, GNSDKERR_InvalidArg)
#define QNXSTGERR_InvalidStorageLocation	GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_QNX, GNSDKERR_FileInvalidFolder)
#define QNXSTGERR_InvalidSchema				GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_QNX, GNSDKERR_InvalidSchema)
#define QNXSTGERR_SchemaMismatch			GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_QNX, GNSDKERR_SchemaMismatch)
#define QNXSTGERR_StatementError			GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_QNX, GNSDKERR_InvalidFormat)
#define QNXSTGERR_EndOfRecords				GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_QNX, GNSDKERR_EndOfRecords)
#define QNXSTGWARN_EndOfRecords				GNSDKERR_MAKE_WARNING(GNSDKPKG_Storage_QNX, GNSDKERR_EndOfRecords)
#define QNXSTGERR_DuplicateRecord			GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_QNX, GNSDKERR_DuplicateRecord)
#define QNXSTGWARN_DuplicateRecord			GNSDKERR_MAKE_WARNING(GNSDKPKG_Storage_QNX, GNSDKERR_DuplicateRecord)
#define QNXSTGERR_StorageFull				GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_QNX, GNSDKERR_FileTooLarge)
#define QNXSTGWARN_StorageFull				GNSDKERR_MAKE_WARNING(GNSDKPKG_Storage_QNX, GNSDKERR_FileTooLarge)
#define QNXSTGERR_ReadOnly					GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_QNX, GNSDKERR_ReadOnly)
#define QNXSTGERR_IOError					GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_QNX, GNSDKERR_IOError)
#define QNXSTGERR_Unknown					GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_QNX, GNSDKERR_Unknown)
#define QNXSTGERR_Unsupported				GNSDKERR_MAKE_ERROR(GNSDKPKG_Storage_QNX, GNSDKERR_Unsupported)

/* Lookup FP Local Errors */
#define LCLFPERR_NoError					GNSDKERR_NoError
#define LCLFPERR_NoMemory					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_FPLocal, GNSDKERR_NoMemory)
#define LCLFPERR_InvalidArg					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_FPLocal, GNSDKERR_InvalidArg)
#define LCLFPERR_InitFailed					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_FPLocal, GNSDKERR_InitFailed)
#define LCLFPERR_NotInited					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_FPLocal, GNSDKERR_NotInited)
#define LCLFPERR_NotFound					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_FPLocal, GNSDKERR_NotFound)
#define LCLFPWARN_NotFound					GNSDKERR_MAKE_WARNING(GNSDKPKG_Lookup_FPLocal, GNSDKERR_NotFound)
#define LCLFPERR_HandleObjectInvalid		GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_FPLocal, GNSDKERR_HandleObjectInvalid)
#define LCLFPERR_InvalidData				GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_FPLocal, GNSDKERR_InvalidData)
#define LCLFPERR_InvalidVersion				GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_FPLocal, GNSDKERR_UnknownVersion)
#define LCLFPERR_UnsupportedAlg				GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_FPLocal, GNSDKERR_UnsupportedAlg)
#define LCLFPERR_Unsupported				GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_FPLocal, GNSDKERR_Unsupported)
#define LCLFPERR_Unknown					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_FPLocal, GNSDKERR_Unknown)
#define LCLFPERR_AlreadyAdded				GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_FPLocal, GNSDKERR_AlreadyAdded)
#define LCLFPERR_InsufficientInputData		GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_FPLocal, GNSDKERR_InsufficientInputData)
#define LCLFPERR_TooMany					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_FPLocal, GNSDKERR_TooMany)
#define LCLFPERR_InvalidDate				GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_FPLocal, GNSDKERR_InvalidDate)
#define LCLFPERR_IncorrectUsage				GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_FPLocal, GNSDKERR_IncorrectUsage)
#define LCLFPERR_LocalDBSchemaMismatch		GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_FPLocal, GNSDKERR_SchemaMismatch)
#define LCLFPERR_LocalDatabaseNotFound		GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_FPLocal, GNSDKERR_LocalDatabaseNotFound)
#define LCLFPWARN_LocalDatabaseNotFound		GNSDKERR_MAKE_WARNING(GNSDKPKG_Lookup_FPLocal, GNSDKERR_LocalDatabaseNotFound)

/* Lookup Local Stream Errors */
#define LSTRERR_NoError						GNSDKERR_NoError
#define LSTRERR_NoMemory					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_LocalStream, GNSDKERR_NoMemory)
#define LSTRERR_InvalidArg					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_LocalStream, GNSDKERR_InvalidArg)
#define LSTRERR_InitFailed					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_LocalStream, GNSDKERR_InitFailed)
#define LSTRERR_NotInited					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_LocalStream, GNSDKERR_NotInited)
#define LSTRERR_NotFound					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_LocalStream, GNSDKERR_NotFound)
#define LSTRWARN_NotFound					GNSDKERR_MAKE_WARNING(GNSDKPKG_Lookup_LocalStream, GNSDKERR_NotFound)
#define LSTRERR_HandleObjectInvalid			GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_LocalStream, GNSDKERR_HandleObjectInvalid)
#define LSTRERR_HandleObjectWrongType		GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_LocalStream, GNSDKERR_HandleObjectWrongType)
#define LSTRERR_InvalidData					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_LocalStream, GNSDKERR_InvalidData)
#define LSTRERR_InvalidVersion				GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_LocalStream, GNSDKERR_UnknownVersion)
#define LSTRERR_UnsupportedAlg				GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_LocalStream, GNSDKERR_UnsupportedAlg)
#define LSTRERR_Unsupported					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_LocalStream, GNSDKERR_Unsupported)
#define LSTRERR_IOError						GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_LocalStream, GNSDKERR_IOError)
#define LSTRERR_AlreadyAdded				GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_LocalStream, GNSDKERR_AlreadyAdded)
#define LSTRWARN_AlreadyAdded				GNSDKERR_MAKE_WARNING(GNSDKPKG_Lookup_LocalStream, GNSDKERR_AlreadyAdded)
#define LSTRERR_InsufficientInputData		GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_LocalStream, GNSDKERR_InsufficientInputData)
#define LSTRERR_TooMany						GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_LocalStream, GNSDKERR_TooMany)
#define LSTRERR_InvalidDate					GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_LocalStream, GNSDKERR_InvalidDate)
#define LSTRERR_IncorrectUsage				GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_LocalStream, GNSDKERR_IncorrectUsage)
#define LSTRERR_LocalDBSchemaMismatch		GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_LocalStream, GNSDKERR_SchemaMismatch)
#define LSTRERR_LocalDatabaseNotFound		GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_LocalStream, GNSDKERR_LocalDatabaseNotFound)
#define LSTRWARN_LocalDatabaseNotFound		GNSDKERR_MAKE_WARNING(GNSDKPKG_Lookup_LocalStream, GNSDKERR_LocalDatabaseNotFound)
#define LSTRERR_LocalDatabaseNotEnabled		GNSDKERR_MAKE_ERROR(GNSDKPKG_Lookup_LocalStream, GNSDKERR_LocalDatabaseNotEnabled)
#define LSTRWARN_LocalDatabaseNotEnabled	GNSDKERR_MAKE_WARNING(GNSDKPKG_Lookup_LocalStream, GNSDKERR_LocalDatabaseNotEnabled)

/* Errors returned from TOCGEN SDK */
#define TOCGENERR_NoError                   GNSDKERR_NoError
#define TOCGENERR_NoMemory                  GNSDKERR_MAKE_ERROR(GNSDKPKG_TOC_Gen, GNSDKERR_NoMemory)
#define TOCGENERR_InitFailed                GNSDKERR_MAKE_ERROR(GNSDKPKG_TOC_Gen, GNSDKERR_InitFailed)
#define TOCGENERR_NotInited                 GNSDKERR_MAKE_ERROR(GNSDKPKG_TOC_Gen, GNSDKERR_NotInited)
#define TOCGENERR_Unsupported               GNSDKERR_MAKE_ERROR(GNSDKPKG_TOC_Gen, GNSDKERR_Unsupported)
#define TOCGENERR_InvalidArg                GNSDKERR_MAKE_ERROR(GNSDKPKG_TOC_Gen, GNSDKERR_InvalidArg)
#define TOCGENWARN_NotApplicable            GNSDKERR_MAKE_WARNING(GNSDKPKG_TOC_Gen, GNSDKERR_NotApplicable)
#define TOCGENERR_InvalidPath               GNSDKERR_MAKE_ERROR(GNSDKPKG_TOC_Gen, GNSDKERR_InvalidPath)
#define TOCGENERR_HandleObjectWrongType     GNSDKERR_MAKE_ERROR(GNSDKPKG_TOC_Gen, GNSDKERR_HandleObjectWrongType)

/* Errors returned from Correlates SDK */
#define CORRSERR_NoError                   GNSDKERR_NoError
#define CORRSERR_NoMemory                  GNSDKERR_MAKE_ERROR(GNSDKPKG_Correlates, GNSDKERR_NoMemory)
#define CORRSERR_InitFailed                GNSDKERR_MAKE_ERROR(GNSDKPKG_Correlates, GNSDKERR_InitFailed)
#define CORRSERR_NotInited                 GNSDKERR_MAKE_ERROR(GNSDKPKG_Correlates, GNSDKERR_NotInited)
#define CORRSERR_InvalidArg                GNSDKERR_MAKE_ERROR(GNSDKPKG_Correlates, GNSDKERR_InvalidArg)
#define CORRSERR_HandleObjectInvalid       GNSDKERR_MAKE_ERROR(GNSDKPKG_Correlates, GNSDKERR_HandleObjectInvalid)
#define CORRSERR_HandleObjectWrongType     GNSDKERR_MAKE_ERROR(GNSDKPKG_Correlates, GNSDKERR_HandleObjectWrongType)

/* Errors returned from Personal Channels SDK */
#define TASTEERR_NoError					GNSDKERR_NoError
#define TASTEERR_NoMemory                   GNSDKERR_MAKE_ERROR(GNSDKPKG_Taste, GNSDKERR_NoMemory)
#define TASTEERR_InitFailed                	GNSDKERR_MAKE_ERROR(GNSDKPKG_Taste, GNSDKERR_InitFailed)
#define TASTEERR_NotInited                 	GNSDKERR_MAKE_ERROR(GNSDKPKG_Taste, GNSDKERR_NotInited)
#define TASTEERR_InvalidArg                	GNSDKERR_MAKE_ERROR(GNSDKPKG_Taste, GNSDKERR_InvalidArg)
#define TASTEERR_HandleObjectInvalid       	GNSDKERR_MAKE_ERROR(GNSDKPKG_Taste, GNSDKERR_HandleObjectInvalid)
#define TASTEERR_HandleObjectWrongType		GNSDKERR_MAKE_ERROR(GNSDKPKG_Taste, GNSDKERR_HandleObjectWrongType)
#define TASTEERR_Busy						GNSDKERR_MAKE_ERROR(GNSDKPKG_Taste, GNSDKERR_Busy)
#define TASTEERR_IckyError					GNSDKERR_MAKE_ERROR(GNSDKPKG_Taste, GNSDKERR_IckyError)
#define TASTEERR_Unexpected					GNSDKERR_MAKE_ERROR(GNSDKPKG_Taste, GNSDKERR_Unexpected)
#define TASTEERR_InvalidCall				GNSDKERR_MAKE_ERROR(GNSDKPKG_Taste, GNSDKERR_InvalidCall)
#define TASTEERR_InvalidData				GNSDKERR_MAKE_ERROR(GNSDKPKG_Taste, GNSDKERR_InvalidData)
#define TASTEWARN_NotApplicable           	GNSDKERR_MAKE_WARNING(GNSDKPKG_Taste, GNSDKERR_NotApplicable)
#define TASTEERR_Unknown					GNSDKERR_MAKE_ERROR(GNSDKPKG_Taste, GNSDKERR_Unknown)
#define TASTEERR_NotFound					GNSDKERR_MAKE_ERROR(GNSDKPKG_Taste, GNSDKERR_NotFound)
#define TASTEERR_InvalidFormat				GNSDKERR_MAKE_ERROR(GNSDKPKG_Taste, GNSDKERR_InvalidFormat)
#define TASTEERR_CorrelateSet				GNSDKERR_MAKE_ERROR(GNSDKPKG_Taste, GNSDKERR_CorrelateSet)
#define TASTEERR_ParamSet					GNSDKERR_MAKE_ERROR(GNSDKPKG_Taste, GNSDKERR_ParamSet)
#define TASTEERR_LocaleNotSet				GNSDKERR_MAKE_ERROR(GNSDKPKG_Taste, GNSDKERR_LocaleNotSet)
#define TASTEERR_BufferTooSmall				GNSDKERR_MAKE_ERROR(GNSDKPKG_Taste, GNSDKERR_BufferTooSmall)
#define TASTEERR_LibraryNotLoaded			GNSDKERR_MAKE_ERROR(GNSDKPKG_Taste, GNSDKERR_LibraryNotLoaded)
#define TASTEERR_InvalidSchema				GNSDKERR_MAKE_ERROR(GNSDKPKG_Taste, GNSDKERR_InvalidSchema)

/* Errors returned from Rhythm SDK */
#define RHYTHMERR_NoError					GNSDKERR_NoError
#define RHYTHMERR_NotInited					GNSDKERR_MAKE_ERROR(GNSDKPKG_Rhythm, GNSDKERR_NotInited)
#define RHYTHMERR_InitFailed				GNSDKERR_MAKE_ERROR(GNSDKPKG_Rhythm, GNSDKERR_InitFailed)
#define RHYTHMERR_InvalidArg				GNSDKERR_MAKE_ERROR(GNSDKPKG_Rhythm, GNSDKERR_InvalidArg)
#define RHYTHMERR_NoMemory					GNSDKERR_MAKE_ERROR(GNSDKPKG_Rhythm, GNSDKERR_NoMemory)
#define RHYTHMERR_SeedRequired				GNSDKERR_MAKE_ERROR(GNSDKPKG_Rhythm, GNSDKERR_SeedRequired)
#define RHYTHMERR_SeedInvalid				GNSDKERR_MAKE_ERROR(GNSDKPKG_Rhythm, GNSDKERR_SeedInvalid)
#define RHYTHMERR_SeedLimitReached			GNSDKERR_MAKE_ERROR(GNSDKPKG_Rhythm, GNSDKERR_SeedLimitReached)
#define RHYTHMERR_SeedsLocked				GNSDKERR_MAKE_ERROR(GNSDKPKG_Rhythm, GNSDKERR_SeedsLocked)
#define RHYTHMERR_HandleObjectInvalid		GNSDKERR_MAKE_ERROR(GNSDKPKG_Rhythm, GNSDKERR_HandleObjectInvalid)
#define RHYTHMERR_HandleObjectWrongType		GNSDKERR_MAKE_ERROR(GNSDKPKG_Rhythm, GNSDKERR_HandleObjectWrongType)
#define RHYTHMERR_NotFound					GNSDKERR_MAKE_ERROR(GNSDKPKG_Rhythm, GNSDKERR_NotFound)
#define RHYTHMERR_IckyError					GNSDKERR_MAKE_ERROR(GNSDKPKG_Rhythm, GNSDKERR_IckyError)



#ifdef __cplusplus
}
#endif

#endif /* _GNSDK_ERROR_CODES_H_ */

